KS_KEYS_CONSTANT(ESCAPE,    Escape,     "Esc")
KS_KEYS_CONSTANT(UP,        Up,         "Up")
KS_KEYS_CONSTANT(DOWN,      Down,       "Down")
KS_KEYS_CONSTANT(LEFT,      Left,       "Left")
KS_KEYS_CONSTANT(RIGHT,     Right,      "Right")
